<#
.SYNOPSIS
    Plays a sound notification (.wav or .mp3 / other) on Windows.
.DESCRIPTION
    Generated by Agent Notifications. Invoked by Claude Code hooks.
    Provide a specific file with -Path, OR a folder with -Folder. With -Folder
    and -Random a random sound from that folder is played on each invocation.
    WAV plays synchronously via System.Media.SoundPlayer; other formats (mp3,
    wma, ...) via System.Windows.Media.MediaPlayer, waiting up to -MaxSeconds.
.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File play_sound.ps1 -Path .\sounds\task-complete\done.wav
.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File play_sound.ps1 -Folder .\sounds\task-complete -Random
#>
param(
    [string]$Path,
    [string]$Folder,
    [switch]$Random,
    [int]$MaxSeconds = 15
)

function Resolve-SoundFile {
    if ($Folder) {
        if (-not (Test-Path -LiteralPath $Folder)) { Write-Error "Folder not found: $Folder"; exit 1 }
        $files = Get-ChildItem -LiteralPath $Folder -File |
            Where-Object { @('.wav', '.mp3') -contains $_.Extension.ToLowerInvariant() }
        if (-not $files) { Write-Error "No .wav/.mp3 files in $Folder"; exit 1 }
        if ($Random) { return ($files | Get-Random).FullName }
        return ($files | Sort-Object Name | Select-Object -First 1).FullName
    }
    if ($Path) {
        if (-not (Test-Path -LiteralPath $Path)) { Write-Error "Sound file not found: $Path"; exit 1 }
        return (Resolve-Path -LiteralPath $Path).Path
    }
    Write-Error "Provide -Path <file> or -Folder <dir> [-Random]"
    exit 1
}

$full = Resolve-SoundFile
$ext = [System.IO.Path]::GetExtension($full).ToLowerInvariant()

try {
    if ($ext -eq '.wav') {
        $player = New-Object System.Media.SoundPlayer
        $player.SoundLocation = $full
        $player.Load()
        $player.PlaySync()   # blocks for the (short) clip duration
    }
    else {
        Add-Type -AssemblyName presentationCore -ErrorAction Stop
        $player = New-Object System.Windows.Media.MediaPlayer
        $player.Open([System.Uri]$full)

        # NaturalDuration is populated asynchronously once the media is opened.
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        while (-not $player.NaturalDuration.HasTimeSpan -and $sw.Elapsed.TotalSeconds -lt 5) {
            Start-Sleep -Milliseconds 50
        }

        $player.Play()
        if ($player.NaturalDuration.HasTimeSpan) {
            $dur = [math]::Ceiling($player.NaturalDuration.TimeSpan.TotalSeconds)
            Start-Sleep -Seconds ([math]::Min($dur, $MaxSeconds))
        }
        else {
            Start-Sleep -Seconds ([math]::Min(5, $MaxSeconds))
        }
        $player.Stop()
        $player.Close()
    }
}
catch {
    Write-Error "Failed to play sound: $_"
    exit 1
}
